os: linux
dist: focal
language: node_js
node_js:
  - 18
cache: npm
services:
  - docker
jobs:
  include:
    - stage: build
      install:
        - npm install
    - stage: test
      before_install:
        - docker run -d --name pitonisa-container jairobankhardt/pitonisa
        - sleep 10 # Pausa para que o container da Pitonisa inicie
      script:
        - npm start &
        # Testes com OWASP ZAP
        - docker run --add-host=host.docker.internal:host-gateway owasp/zap2docker-stable zap-baseline.py -t "http://host.docker.internal:3000" -I
      after_failure:
        # Em caso de falha, você pode adicionar ações para lidar com a falha, se necessário
        - echo "Testes com OWASP ZAP falharam"
    - stage: deploy
      install:
        - npm install netlify-cli -g
        - npm install --save react react-dom react-scripts
      script:
        # Netlify
        - yarn build
        - netlify deploy --prod --dir=build
      after_script:
        # Enviar uma mensagem para o Telegram
        - bash ./telegram_notification.sh
        - echo "Pitonisa está on"