os: linux
dist: focal
language: node_js
node_js:
  - 18
cache: npm
services:
  - docker
jobs:
  include:
    - stage: build
      install:
        - npm install
    - stage: test
      before_install:
        - docker run -d --name pitonisa-container jairobankhardt/pitonisa
        - sleep 10 # Espera um pouco para que o container da Pitonisa inicie
      script:
      - npm start &
        # Testes - OWASP ZAP
        - docker run --network host owasp/zap2docker-stable zap-baseline.py -t "http://localhost:3000" -I
      after_failure:

        - echo "Testes com OWASP ZAP falharam"
    - stage: deploy
    install:
        - npm install netlify-cli
      script:
        # Netlify
        - npm run build
        - netlify deploy --prod --dir=./build
      after_script:
        - bash ./telegram_notification.sh
        - echo "Pitonisa está on"
