language: node_js
cache: npm
jobs:
  include:
    - stage: build
      install:
        - npm install

    - stage: test
      script:
        - npm start
        
    - stage: deploy
      after_script:
        # Em caso de sucesso enviará uma mensagem para o telegram
        - bash ./telegram_notification.sh
        - echo "Pitonisa está on"