os: linux
dist: focal
language: node_js
node_js:
  - 18
cache: npm
services:
  - docker
jobs:
  include:
    - stage: build
      install:
        - npm install
    - stage: test
      before_install:
        - docker run -d --name pitonisa-container jairobankhardt/pitonisa
        - sleep 10 # Espera um pouco para que o container da Pitonisa inicie
      script:
        - npm start
        # Rodar os testes com OWASP ZAP no host e ignorar os warnings
        - docker run --add-host=host.docker.internal:host-gateway owasp/zap2docker-stable zap-baseline.py -t "http://host.docker.internal:3000" -I
      after_failure:
        # Em caso de falha, você pode adicionar ações para lidar com a falha, se necessário
        - echo "Testes com OWASP ZAP falharam"
    - stage: deploy
      script:
        # Implemente a aplicação para o Netlify (substitua com seus comandos de implantação reais)
        - npm run build
        - netlify deploy --prod --dir=./build
      after_script:
        # Em caso de sucesso, enviar uma mensagem para o Telegram
        - bash ./telegram_notification.sh
        - echo "Pitonisa está on"